---

- hosts: localhost
  tasks:
  - include_vars: config.yml

- include: playbooks/homebrew.yml

- hosts: localhost
  tasks:

    - name: notify success
      shell: osascript -e 'display notification "Boxam run finished" with title "Boxam"'
